### ISSUE TITLE
Metadata for searches

### ISSUE THREAD

**Issue by jessicablois** [NeotomaDB/Explorer#1]
When I perform a search in Explorer, a little message appears with some basic search statistics (e.g., "551 sites with 665 datasets found").  Then this message goes away.  The search itself is saved in the "Current Searches" window, but without the summary stats.  Is there any way to add this summary data to the search? It would be useful information to have, without having to download all sites or count them manually.

**Comment by SimonGoring** [comment]
Are you talking about a rollover textbox?  So that if you hover over the item in the tray it would say:

Advanced Search
532 Sites
Something Something

Or are you talking about a metadata README file that would be in the zip of your tray items?

**Comment by jessicablois** [comment]
I'd be happy with either.  What appears is similar to rollover text, but it disappears after a second or so, and you can't get that information back.

**Comment by spatialit** [comment]
There was already a rollover message containing the dataset count for the search. I changed it to show both the site and dataset count. You have to hover over the search row for a second or so for the popup to appear.

**Comment by jessicablois** [comment]
OK, thanks.  Could we add this to the Help documentation for Explorer?
Also, there are a few other features of the Help documentation that need
updating.  Is this something I have access to to do myself, or should I
send along those notes to someone else?

Best,
Jessica

------------------------------------------
Assistant Professor
School of Natural Sciences
University of California, Merced

Office: SE1 296
Phone: (209) 228-2256
Email: jblois@ucmerced.edu
Web: http://jessicablois.com

**Comment by SimonGoring** [comment]
I think we should try to standardize or help documentation, this is all part of website development, and I think Mike Stryker should be in on this.

I'm going to close this issue and raise a new issue about the help.

**Comment by spatialit** [comment]
I looked at both DokuWiki and HelpNDoc. DokuWiki, or something similar, is what we want. It allows distributed editing and includes access control. Seems like both have a "source" version and the generated documents. I asked Brian where the source is but haven't heard back.

**Comment by SimonGoring** [comment]
For Explorer, sure, for the API I think it would be better to have something self-documenting like [APIDoc.js](http://apidocjs.com/) (assuming an eventual move over to the more transparent node.js RESTful API.
