### ISSUE TITLE
Search drop down menus don't show all choices

### ISSUE THREAD

**Issue by ecgrimm** [NeotomaDB/Explorer#13]
In the search box, drop down menus (e.g. for Database) don't show all the selections. You have to type a letter (e.g. 'N'), which will then show you the databases beginning with that letter. This is very inconvenient, because users may have no idea which databases are available.

**Comment by stryker-m** [comment]
Full list of options now displays in Advanced search form.

**Comment by stryker-m** [comment]
closed with prior comment.
