### ISSUE TITLE
X-axis for chronology graph reversed

### ISSUE THREAD

**Issue by ecgrimm** [NeotomaDB/Explorer#19]
For DatasetID 27166 (Lago Grande di Monticchio), the X-axis is reversed. It turns out the depths were reversed in the upload file, so the greater AnalysisUnitID's have decreasing ages, but, nevertheless, the X-axis on the graph should increase from left to right. This dataset is from a short section of core, and there are no labelled tic marks on the graph.

![image](https://user-images.githubusercontent.com/20047615/40640541-174ca974-62dc-11e8-8f51-17cf03edbaca.png)

**Comment by IceAgeEcologist** [comment]
This is a data issue; removing it from the 'Explorer' issues list.
