### ISSUE TITLE
Search: Search by Constituent Database

### ISSUE THREAD

**Issue by IceAgeEcologist** [NeotomaDB/Explorer#33]

**Comment by IceAgeEcologist** [comment]
Suggest adding in Advanced Search, right under the search box for Dataset Type, a new search enabling searches by Constituent Databases

**Comment by stryker-m** [comment]
This option is available under the Metadata search parameters though it is labeled "Databases".  Here's a screen shot.
![image](https://user-images.githubusercontent.com/4348774/57020511-7d03b580-6bf7-11e9-9ca4-909d69675e3b.png)

**Comment by IceAgeEcologist** [comment]
Ah good!  Sorry for missing this.
