### ISSUE TITLE
Developing an intuitive high-level-interface for neotoma

### ISSUE THREAD

**Issue by Chilipp** [NeotomaDB/Explorer#37]
Hi everyone!

after Simon's great workshop this morning I'd like to discuss some idea of a new web application for Neotoma. I already implemented something comparable for the Eurasian Modern Pollen Database (EMPD2) that is hosted at https://empd2.github.io. I am also working on a paper that I submit to the Journal of Open Source Software (see [here](https://github.com/EMPD2/EMPD-data/blob/joss/joss/paper.pdf)) but I will implement more tests for the viewer and cleaning it up. However, here are some highlights that might be of interest:

- The EMPD-viewer loads the data from the Github repository upon request which allows us to manage new data contributions through a Github Pull Request
- A webapp that is hosted at https://empd-admin.herokuapp.com can be used to manage and test contributions from within a pull request and it manages issues of the database that are [submitted through the viewer](https://empd2.github.io?tab=report-issue) and raised at the [github repository](https://github.com/EMPD2/EMPD-data/issues) of the database.

I also implemented a comparable interface for our large northern hemispheric pollen database (that incorporates the samples of Neotoma) but that is not yet ready to be shared. I will, however, show this in my [INQUA talk on Wednesday](https://app.oxfordabstracts.com/events/574/program-app/submission/94623). This application provides also the functionality of overlaying the data with the gridded reconstructions or anything else.

The good thing about this framework (in particular the viewer) is that it is relatively simple and provides a good overview about the content of the database. The Neotoma Explorer is great but I have the impression that people tend to get overwhelmed by the amount of functionality and complexity that is inherent to such a broad database interface application. The small webapp that I am discussing here would require to focus on some essential meta data information that can be visualized in the viewer and the data is then pulled of from Neotoma through the web API.

But this is just an Idea and it would be very nice to know, what you are thinking about it. To be honest with you, I am currently finishing my PhD and start a new position in December that is not so much related to pollen anymore (but still with research and web development). Therefore I am super busy at the moment but, nevertheless I'd be happy to work on it if there is interest and room for collaboration. I think this would be a nice application that is not too difficult to be implemented.

Best wishes,
Philipp

**Comment by IceAgeEcologist** [comment]
Good ideas, have made a copy of this for future reference.  Closing this as an active issue.
