### ISSUE TITLE
Explorer taxon gear window doesn't show dropdown arrow.

### ISSUE THREAD

**Issue by SimonGoring** [NeotomaDB/Explorer#9]
When I use the gears to modify my search by taxon the upper box (Taxa Group) should be presenting a drop down selection box, but I can't drop it down because the down arrow isn't visible.  I can type in the bo and get the selections, but I can't click on it to get all the options.

![image](https://cloud.githubusercontent.com/assets/1619126/24371081/918f5622-12de-11e7-8291-39d40c84f612.png)

**Comment by stryker-m** [comment]
Fixed.  FilteringSelect widget width was set incorrectly (set as 240px, should be 204px).
